---
site_name: Gnosis
repo_url: https://github.com/Consensys/gnosis
site_description: Gnosis Documentation
theme: readthedocs
extra_css: [extra.css]
pages:
- Introduction: 'index.md'
- Getting Started:
  - Installation: 'getting-started/installation.md'
  - Instance/Config: 'getting-started/instance.md'
  - Transactions and calls: 'getting-started/transactions-and-calls.md'
  - New prediction market: 'getting-started/new-prediction-market.md'
  - Get events: 'getting-started/get-events.md'
  - State: 'getting-started/state.md'
  - Trading: 'getting-started/trading.md'
- Reference:
  - Introduction: 'reference/introduction.md'
  - REST API: 'reference/api.md'
  - Contracts:
    - Index: 'reference/contracts/index.md'
    - Events: 'reference/contracts/events.md'
    - Market: 'reference/contracts/market.md'
    - Market maker: 'reference/contracts/market-maker.md'
  - Event description: 'reference/event-description.md'
  - Event-on-chain: 'reference/event.md'
