---
site_name: Gnosis
repo_url: https://github.com/Consensys/gnosis
site_description: Gnosis Documentation
theme: readthedocs
extra_css: [extra.css]
pages:
- Introduction: 'index.md'
- Getting Started:
  - Installation: 'getting_started/installation.md'
  - Instance/Config: 'getting_started/instance.md'
  - Transactions and calls: 'getting_started/transactionsAndCalls.md'
  - New prediction market: 'getting_started/newPredictionMarket.md'
  - Get events: 'getting_started/getEvents.md'
  - State: 'getting_started/state.md'
  - Trading: 'getting_started/trading.md'
- Reference:
  - Introduction: 'api_reference/introduction.md'
  - REST API: 'api_reference/api.md'
  - Event description: 'api_reference/eventDescription.md'
